#!/bin/bash

USERNAME=$(basename "$1")
API_URL="https://api.github.com/users/$USERNAME/repos"
OUTPUT_FILE="${USERNAME}.txt"

curl -s "$API_URL" | jq -r '.[].name' > "$OUTPUT_FILE"

echo "Repositories saved to $OUTPUT_FILE"
